library(dada2);packageVersion("dada2")
setwd("/home/svu/e0453664/Projects/MarineMicrobiome")

# Import PS_PL seqtab and add taxonomy (excluding species)
print("Loading PS_PL taxonomy RDS file...")
seqtab.nochloro.PS_PL <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-PS-PL-PNG-16s.RDS")
print("Running taxonomy assignment ...")
taxa.PS_PL <- assignTaxonomy(seqtab.nochloro.PS_PL, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.PS_PL <- addSpecies(taxa.PS_PL, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.PS_PL, "./Outputs/Silva_Taxonomy-PS_PL-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.PS_PL)
rm(taxa.PS_PL)

# Import DH_PA seqtab and add taxonomy (excluding species)
print("Loading DH_PA taxonomy RDS file...")
seqtab.nochloro.DH_PA <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-DH-PA-PNG-16s.RDS")
print("Running taxonomy assignment ...")
taxa.DH_PA <- assignTaxonomy(seqtab.nochloro.DH_PA, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.DH_PA <- addSpecies(taxa.DH_PA, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.DH_PA, "./Outputs/Silva_Taxonomy-DH_PA-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.DH_PA)
rm(taxa.DH_PA)

# Import EW_1 seqtab and add taxonomy (excluding species)
print("Loading EW_1 taxonomy RDS file...")
seqtab.nochloro.EW_1 <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-EW-1-16s.RDS")
print("Running taxonomy assignment ...")
taxa.EW_1 <- assignTaxonomy(seqtab.nochloro.EW_1, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.EW_1 <- addSpecies(taxa.EW_1, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.EW_1, "./Outputs/Silva_Taxonomy-EW_1-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.EW_1)
rm(taxa.EW_1)

# Import EW_2 seqtab and add taxonomy (excluding species)
print("Loading EW_2 taxonomy RDS file...")
seqtab.nochloro.EW_2 <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-EW-2-16s.RDS")
print("Running taxonomy assignment ...")
taxa.EW_2 <- assignTaxonomy(seqtab.nochloro.EW_2, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.EW_2 <- addSpecies(taxa.EW_2, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.EW_2, "./Outputs/Silva_Taxonomy-EW_2-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.EW_2)
rm(taxa.EW_2)

# Import AA seqtab and add taxonomy (excluding species)
print("Loading AA taxonomy RDS file...")
seqtab.nochloro.AA <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-AA-16s.RDS")
print("Running taxonomy assignment ...")
taxa.AA <- assignTaxonomy(seqtab.nochloro.AA, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.AA <- addSpecies(taxa.AA, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.AA, "./Outputs/Silva_Taxonomy-AA-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.AA)
rm(taxa.AA)

# Import SA seqtab and add taxonomy (excluding species)
print("Loading SA taxonomy RDS file...")
seqtab.nochloro.SA <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-SA-16s.RDS")
print("Running taxonomy assignment ...")
taxa.SA <- assignTaxonomy(seqtab.nochloro.SA, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.SA <- addSpecies(taxa.SA, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.SA, "./Outputs/Silva_Taxonomy-SA-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.SA)
rm(taxa.SA)

# Import EA seqtab and add taxonomy (excluding species)
print("Loading EA taxonomy RDS file...")
seqtab.nochloro.EA <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-EA-16s.RDS")
print("Running taxonomy assignment ...")
taxa.EA <- assignTaxonomy(seqtab.nochloro.EA, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.EA <- addSpecies(taxa.EA, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.EA, "./Outputs/Silva_Taxonomy-EA-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.EA)
rm(taxa.EA)

# Import TH seqtab and add taxonomy (excluding species)
print("Loading TH taxonomy RDS file...")
seqtab.nochloro.TH <- readRDS(file = "./Inputs/final_clean_dada2_seqtable-TH-16s.RDS")
print("Running taxonomy assignment ...")
taxa.TH <- assignTaxonomy(seqtab.nochloro.TH, "../tax/silva_nr99_v138.1_train_set.fa.gz", multithread = TRUE)
print("Taxa completed.")
print("Species started ...")
taxa.TH <- addSpecies(taxa.TH, "../tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(taxa.TH, "./Outputs/Silva_Taxonomy-TH-16s.RDS")
print("Script completed.")
rm(seqtab.nochloro.TH)
rm(taxa.TH)
